name: Helm release

on:
  push:
    tags:
      - "helm-chart-*"

jobs:
  index:
    name: Helm index
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Dispatch helm index workflow
        run: gh workflow run helm-index.yaml --repo mmontes11/test
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
