name: Helm release

on:
  push:
    tags:
      - "helm-chart-*"

jobs:
  index:
    name: Helm index
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch helm index workflow
        run: gh workflow run helm-index.yml --repo mmontes11/test
        env:
          GITHUB_TOKEN: "${{ secrets.GHA_TOKEN }}"
